### ISSUE TITLE
fix broken test and improve error message

### ISSUE THREAD

**Issue by mess110** [dilcom/pilot-gnuplot#28]
Tests fail with 1 error:

```
Failures:

  1) GnuplotRB::Plot#to_iruby should handle output to iRuby
     Failure/Error: expect(Plot.new(['sin(x)'], term: term).to_iruby[0]).to eql(type)
     ArgumentError:
       Seems like your Gnuplot does not support that terminal, please see supported terminals with Settings::available_terminals
     # ./lib/gnuplotrb/mixins/option_handling.rb:106:in `validate_terminal_options'
     # ./lib/gnuplotrb/plot.rb:28:in `initialize'
     # ./spec/plot_spec.rb:186:in `new'
     # ./spec/plot_spec.rb:186:in `block (4 levels) in <top (required)>'
     # ./spec/plot_spec.rb:185:in `each'
     # ./spec/plot_spec.rb:185:in `block (3 levels) in <top (required)>'
```
1. This test should be fixed
2. In the error message, it would be nice to display which terminal is missing instead of 'that terminal'
